[package]
name = "_struct"
version = "0.1.0"
authors = ["jhaemin <io@jhaemin.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
